# Generated by Django 4.0.3 on 2022-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(default='static/img/default2.png', upload_to='media/student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='static/img/default3.png', upload_to='media/student'),
        ),
    ]
