# Generated by Django 4.0.3 on 2022-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_lecturer_image_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(default='media/default1.webp', upload_to='staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='media/default1.webp', upload_to='student'),
        ),
    ]
