# Generated by Django 4.0.3 on 2022-04-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0005_alter_lecturer_image_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_code', models.CharField(blank=True, max_length=100, null=True)),
                ('instruction', models.TextField(blank=True, max_length=1000, null=True)),
                ('no_of_question', models.IntegerField(blank=True, null=True)),
                ('minite_to_finish', models.IntegerField(choices=[(20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50)], default=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='questions')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.lecturer')),
            ],
        ),
    ]
