# Generated by Django 4.0.3 on 2022-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
