# Generated by Django 4.0.3 on 2022-04-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
