# Generated by Django 4.0.3 on 2022-04-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='done',
            new_name='is_done',
        ),
    ]
