# Generated by Django 4.0.3 on 2022-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
