# Generated by Django 4.0.3 on 2022-04-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='count',
        ),
    ]
