# Generated by Django 4.0.3 on 2022-04-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_question_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
